update mcsv script

diff --git a/mcsv b/mcsv
--- a/mcsv
+++ b/mcsv
@@ -1,45 +1,60 @@
 #!/bin/sh
 
-server_path="papermc"
-NAME="mcsv"
-
-ztkey="$HOME/.mcsv.ztkey"
-ztnet="$HOME/.mcsv.ztnet"
-if [ ! -f "$ztkey" ]; then
-    docker run -d --name getztkey --rm --cap-add NET_ADMIN --device /dev/net/tun zerotier/zerotier:latest
-    docker exec getztkey zerotier-idtool generate > "$ztkey"
-    docker stop getztkey
+if ! command -v java >/dev/null 2>&1; then
+    echo "Java is not installed, please install latest java version (current java21)"
+    exit 1
 fi
-if [ ! -f "$ztnet" ] || [ -z "$(cat "$ztnet" )" ]; then
-    printf "Please enter ZeroTier Network ID: "
-    read -r id
-    echo "$id" > "$ztnet"
-fi
+run_zt_on_docker() {
+    if ! command -v docker >/dev/null 2>&1; then
+        echo "Docker is not installed!"
+        echo "Please install docker and re-run this script with z flag"
+        echo "OR"
+        echo "Install and configure Zerotier manually"
+        exit 1
+    fi
+    name="mcsv" # Container name
+    ztkey="$HOME/.mcsv.ztkey"
+    ztnet="$HOME/.mcsv.ztnet"
+    if [ ! -f "$ztkey" ]; then
+        docker run -d --name getztkey --rm --cap-add NET_ADMIN --device /dev/net/tun zerotier/zerotier:latest
+        docker exec getztkey zerotier-idtool generate > "$ztkey"
+        docker stop getztkey
+    fi
+    if [ ! -f "$ztnet" ] || [ -z "$(cat "$ztnet" )" ]; then
+        printf "Please enter ZeroTier Network ID: "
+        read -r id
+        echo "$id" > "$ztnet"
+        znetid="$(cat "$ztnet" )"
+        zidpublic="$(sed 's/:/\n/3' "$ztkey" | head -n1)"
+        zidsecret="$(cat "$ztkey")"
+        docker run \
+        -d \
+        --rm \
+        --net=host \
+        --name "$name" \
+        --env ZEROTIER_IDENTITY_PUBLIC="$zidpublic" \
+        --env ZEROTIER_IDENTITY_SECRET="$zidsecret" \
+        --cap-add NET_ADMIN \
+        --device /dev/net/tun \
+        zerotier/zerotier:latest \
+        "$znetid"
+    fi
+}
 
-ZNETID="$(cat "$ztnet" )"
-ZIDPUBLIC="$(sed 's/:/\n/3' "$ztkey" | head -n1)"
-ZIDSECRET="$(cat "$ztkey")"
+while getopts 'zr' opt; do
+    case "$opt" in
+        z) run_zt_on_docker ;;
+        r) rmworld=true ;;
+        *) echo "Invalid option!" ;;
+    esac
+done
+shift $((OPTIND-1))
 
-docker run \
-    -d \
-    --rm \
-    --net=host \
-    --name "$NAME" \
-    --env ZEROTIER_IDENTITY_PUBLIC="$ZIDPUBLIC" \
-    --env ZEROTIER_IDENTITY_SECRET="$ZIDSECRET" \
-    --cap-add NET_ADMIN \
-    --device /dev/net/tun \
-    zerotier/zerotier:latest \
-    "$ZNETID"
+[ -z "$1" ] && echo "Please specify Server version (the name of the folder contain server jar file)" && exit 1
 
-sudo update-java-alternatives --set java-1.21.0-openjdk-amd64
-
-pwd=$PWD
-cd "$server_path" || exit
-if [ "$1" = "r" ]; then
-    echo "##### Removing existing world... #####"
-    rm -rfv ops.json permissions.yml usercache.json world*
-fi
+pwd=$PWD; cd "$1" || exit 1
+[ "$rmworld" = true ] && rm -rfv ops.json permissions.yml usercache.json world*
+sudo update-java-alternatives --set java-1.21.0-openjdk-amd64 || java --version
 java -Xmx4096M \
     -Xms4096M \
     -XX:+AlwaysPreTouch \
@@ -62,5 +77,5 @@ java -Xmx4096M \
     -XX:SurvivorRatio=32 \
     -Dusing.aikars.flags=https://mcflags.emc.gs \
     -Daikars.new.flags=true \
-    -jar server.jar nogui
-cd "$pwd" || exit
+    -jar ./*.jar nogui
+cd "$pwd" || exit 1
